[package]
name = "into_string"
description = "Helper crate to convert values into strings avoiding extra allocations"
authors = ["Alex Andreba <aandrebafreelancer@gmail.com>"]
repository = ""
version = "1.0.0"
edition = "2021"